### ISSUE TITLE
Setup Firebase backend

### ISSUE THREAD

**Issue by hoanghm** [hoanghm/Proact#19]
- [x] Create a Firebase account
- [x] Storage #11
    - [x] Setup a Firestore db instance
    - [x] Setup unstructured cloud storage instance
- [x] Setup an Authentication instance
- [x] Share the instances with team

**Comment by ogallagher** [comment]
firebase project = [gemini-proact](https://console.firebase.google.com/project/gemini-goalkeeper-2024/overview)

**Comment by hoanghm** [comment]
- Cloud Firestore instance initialized with a single User collection. 
- Empty Cloud Storage instance was initialized with default rules without any user restriction (anyone can do anything).
