### ISSUE TITLE
Initial Database Design

### ISSUE THREAD

**Issue by hoanghm** [hoanghm/Proact#22]
- [x] Determine a list of tables needed
- [x] Identify relationships among tables
- [x] Create such tables in Cloud Firestore
- [ ] Review with the team 

[DB architecture diagram in Miro](https://miro.com/app/board/uXjVK5M77x0=/)

**Comment by ogallagher** [comment]
Database design draft 1 in Slack https://geminiapidevc-avv1250.slack.com/archives/C077XFFPTFH/p1718766091630289

**Comment by hoanghm** [comment]
Proposed design 

![Image](https://github.com/hoanghm/Proact/assets/39893036/a6023e61-aa0a-4ce3-af0e-c4442a2387e7)
