### ISSUE TITLE
Application architecture v1

### ISSUE THREAD

**Issue by hoanghm** [hoanghm/Proact#23]
- Analyze and decide if we need an API to handle the backend stuff, or if Firebase as the backend and Flutter as the frontend should offer everything we need.
- Can (optionally) build on top / modify the diagram in the "Application Design" page. This is the invite link to the Miro board to access the diagram: [Miro Team Invite](https://miro.com/welcomeonboard/NDR4UnBCTkI1N3E5UHVJZkFvcUdnR1o0a1FwMXhuSGp4Y09DSzVmajdlY0gwUjAyblExdTdXbWRTY0hnMmt5a3wzNDU4NzY0NTE0NjM3NTkzNzIzfDI=?share_link_id=41747353563)

**Comment by ogallagher** [comment]
Link to section in Notion https://www.notion.so/Application-Design-2dc3182439194ea7a11c388be07917a1#0ea15ab0eba0412e81ba37e58bdfd3ce

**Comment by ogallagher** [comment]
I think any further details w architecture can be determined as needed.
