### ISSUE TITLE
Testing of dynamic component rendering

### ISSUE THREAD

**Issue by moyeshkhanal** [hoanghm/Proact#4]
## Create and test dynamic component offered by LLM
- [x] Create test project
- [x] Connect Gemini API #14
- [ ] Construct Prompt for Gemini to get code
- [ ] Generate dynamic component and render it #7
- [ ] Test different components
- [ ] Consolidate findings for group

**Comment by ogallagher** [comment]
How to link existing issue to existing project task? https://github.com/users/hoanghm/projects/2/views/1?pane=issue&itemId=67396868

**Comment by hoanghm** [comment]
I think this is no longer relevant?

**Comment by ogallagher** [comment]
@hoanghm I think it's relevant if we still plan to have gemini help customize how components are placed and styled in the frontend.
