### ISSUE TITLE
Set up an 2 API endpoints for new "missions" generation.

### ISSUE THREAD

**Issue by hoanghm** [hoanghm/Proact#65]
- [x] Make sure outputs are json-parsable (Can split this into 2 steps: 1. Generate task --> 2. Format task to JSON)
- [x] Add an API endpoints for **weekly** mission generation
- [x] Add an API endpoint for **ongoing** mission generation
 - Endpoints format:
   ```json
      "// Input"
      {
        "user_id":  "str", 
        "num_missions": "int" 
      }
    
      "// Output"
      {
        "new_missions": [
          {
            "id": "...",
            "title": "...",
            "description": "..."
            "steps": "..."
          },
        ]
      }
    ```

**Comment by hoanghm** [comment]
Added 2 endpoints:
- `GET /get_weekly_missions/<user_id>/<num_missions>`
- `GET /get_ongoing_missions/<user_id>/<num_missions>`

Both return responses of the format
```JSON
{
     "new_missions": [
         {
           "id": "...",
           "title": "...",
           "description": "..."
           "steps": "..."
         },
         // ... there can be multiple missions generated
     ]
   }
```

**Comment by ogallagher** [comment]
We may not use these endpoints if frontend directly queries the firestore db.
